<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="34337" started-at="2019-12-09T13:29:31 IST" finished-at="2019-12-09T13:30:06 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="34337" started-at="2019-12-09T13:29:31 IST" finished-at="2019-12-09T13:30:06 IST">
      <class name="com.training.sanity.tests.TestCases">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.TestCases@79be0360]" name="setUpBeforeClass" is-config="true" duration-ms="16" started-at="2019-12-09T13:29:31 IST" finished-at="2019-12-09T13:29:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.TestCases@79be0360]" name="setUp" is-config="true" duration-ms="27713" started-at="2019-12-09T13:29:31 IST" finished-at="2019-12-09T13:29:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="tc2_UFM_006_ChangePassword()[pri:0, instance:com.training.sanity.tests.TestCases@79be0360]" name="tc2_UFM_006_ChangePassword" duration-ms="4734" started-at="2019-12-09T13:29:59 IST" finished-at="2019-12-09T13:30:04 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error message is not Matching expected [Pass confirmation does not match password!] but found [Password confirmation does not match password!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error message is not Matching expected [Pass confirmation does not match password!] but found [Password confirmation does not match password!]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.training.pom.LoginPOM.validateErrorMsgForPwdChg(LoginPOM.java:140)
at com.training.sanity.tests.TestCases.tc2_UFM_006_ChangePassword(TestCases.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2_UFM_006_ChangePassword -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.TestCases@79be0360]" name="tearDown" is-config="true" duration-ms="1825" started-at="2019-12-09T13:30:04 IST" finished-at="2019-12-09T13:30:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.TestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
